[package]
name = "wasm-supreme-chainsaw"
version = "0.1.0"
authors = ["Ivan Towlson"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
